### ISSUE TITLE
confusion about logging

### ISSUE THREAD

**Issue by ghost** [writeas/pherephone#4]
There are two loggers, both with loglevel error enabled, their useage seems mixed without distinction. Should the logger `printer` be removed and just use `log`?

**Comment by qwazix** [comment]
`printer` does not show the info (filename, time etc on the left) it is used to display nicely formatted stuff such as the name of the app and the actors being followed when the app starts, while `log` is used for debugging purposes and logging filename and line of code is essential.

I was using `fmt.PrintLn` instead of `printer` but I switched it for some reason I don't recall now.
